# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: oak9 Analysis Task@2
  inputs:
    serviceEndpoint: 'oak9 Integration Testing'
    projectName: 'proj-autotesting-3'
    environmentName: 'env-autotesting-3GUR96Zc'
    qualityGate: 'None'
    pollingTimeoutSec: '300'
    oak9APIEndpoint: https://devapi.oak9.cloud
